[package]
edition = "2021"
name = "pacman_test"
version = "0.1.0"

[dev-dependencies]
proptest = "1"
pretty_assertions = "1"
array2d="0.3.0"



[[test]]
doc = true
name = "integration_indep_test"
path = "test/integration_indep_test.rs"
test = true